app/eval/models.py
from app import db
from app.catalog.models import Article
from app.auth.models import User


class Evaluation(db.Model):
    __tablename__ = 'evaluation'

    id = db.Column(db.Integer, primary_key=True)
    form_id = db.Column(db.Integer, nullable=False)
    category = db.Column(db.String(80), nullable=False)
    comments = db.Column(db.String(1000))
    article_id = db.Column(db.Integer, db.ForeignKey('article.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def __init__(self, form_id, category, comments, article_id, user_id):
        self.form_id = form_id
        self.category = category
        self.comments = comments
        self.article_id = article_id
        self.user_id = user_id

    @classmethod
    def create_evaluation(cls, form_id, category, comments, article_id, user_id):
        evaluation = cls(form_id, category, comments, article_id, user_id)
        db.session.add(evaluation)
        db.session.commit()
        return evaluation

    def __repr__(self):
        return 'News article titled "{}" is categorized as {} by user {}'.format(
            Article.query.get(self.article_id).title,
            self.category,
            User.query.get(self.user_id).user_email
        )

app/eval/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField, SelectField, FieldList, FormField, HiddenField
from wtforms.validators import Length


class EvaluateArticleForm(FlaskForm):
    article_id = HiddenField()
    category = SelectField('Category', choices=[
        ('real', 'Legitimate'), ('fake', 'Fake'), ('satire', 'Satire'),
        ('bias', 'Biased Reporting'), ('conspiracy', 'Conspiratorial Thinking'),
        ('opinion', 'Opinion'), ('bad', 'Not a Valid Article (please explain why in the Comment box)')])
    comment = TextAreaField('Comment', validators=[Length(max=1000)])


class EvaluateManyArticlesForm(FlaskForm):
    evals = FieldList(FormField(EvaluateArticleForm), min_entries=20)
    submit = SubmitField('Submit')

app/eval/__init__.py
# app/auth/__init__.py
from flask import Blueprint
eval1 = Blueprint('eval1', __name__, template_folder='templates')
from app.eval import routes

app/eval/routes.py
from app.eval import eval1
from app import db
from app.eval.models import Evaluation
from app.catalog.models import Publication, Article
from flask_security import current_user
from flask import render_template, flash, request, redirect, url_for
from flask_login import login_required
from app.eval.forms import EvaluateArticleForm, EvaluateManyArticlesForm
import numpy as np
import random

@eval1.route('/evaluation', methods=['GET', 'POST'])
@login_required
def display_eval_form():
    form = EvaluateManyArticlesForm(request.form)

    if form.validate_on_submit():
        form_id = np.random.randint(10000000)
        for entry in form.evals.entries:
            Evaluation.create_evaluation(form_id=form_id,
                                         category=entry.data['category'],
                                         comments=entry.data['comment'],
                                         article_id=int(entry.data['article_id']),
                                         user_id=current_user.id)
        return render_template('evaluation_results.html', form_id=form_id)

    test_articles = Article.query.filter_by(is_gold=False).all()
    gold_articles = Article.query.filter_by(is_gold=True).all()
    articles = list(np.random.choice(test_articles, size=10, replace=False))
    articles.extend(gold_articles[:10])
    random.shuffle(articles)

    cnt = 0
    for article_form in form.evals.entries:
        article_form.article_id.data = str(articles[cnt].id)
        cnt += 1

    return render_template('evaluation_prompt.html', EvalForm=form, Articles=articles, zip=zip)

# @main.route('/display/publisher/<publisher_id>')
# def display_publisher(publisher_id):
#     publisher = Publication.query.filter_by(id=publisher_id).first()
#     publisher_books = Book.query.filter_by(pub_id=publisher.id).all()
#     return render_template('publisher.html',
#                            publisher=publisher,
#                            publisher_books=publisher_books)
#
#
# @main.route('/book/delete/<book_id>', methods=['GET', 'POST'])
# @login_required
# def delete_book(book_id):
#     book = Book.query.get(book_id)
#     if request.method == 'POST':
#         db.session.delete(book)
#         db.session.commit()
#         flash('book delete successfully')
#         return redirect(url_for('main.display_books'))
#     return render_template('delete_book.html', book=book, book_id=book.id)
#
#
# @main.route('/evaluation', methods=['GET', 'POST'])
# @login_required
# def eval_books():
#     book = Book.query.get(book_id)
#     form = EditBookForm(obj=book)
#     if form.validate_on_submit():
#         book.title = form.title.data
#         book.format = form.format.data
#         book.num_pages = form.num_pages.data
#         db.session.add(book)
#         db.session.commit()
#         flash('Book Edited Successfully')
#         return redirect(url_for('main.display_books'))
#     return render_template('edit_book.html', form=form)
#
#
# @main.route('/create/book/<pub_id>', methods=['GET', 'POST'])
# @login_required
# def create_book(pub_id):
#     form = CreateBookForm()
#     form.pub_id.data = pub_id  # pre-populates pub_id
#     if form.validate_on_submit():
#         book = Book(title=form.title.data, author=form.author.data, avg_rating=form.avg_rating.data,
#                     book_format=form.format.data, image=form.img_url.data, num_pages=form.num_pages.data,
#                     pub_id=form.pub_id.data)
#         db.session.add(book)
#         db.session.commit()
#         flash('Book added successfully')
#         return redirect(url_for('main.display_publisher', publisher_id=pub_id))
#     return render_template('create_book.html', form=form, pub_id=pub_id)

app/eval/templates/evaluation_prompt.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
<div class="panel panel-default">
      <div class="panel-heading"><h2>Form</h2></div>
      <div class="panel-body">
            <form action="{{ url_for('eval1.display_eval_form') }}" method="POST">
                {{ EvalForm.hidden_tag() }}
                 <div class="panel-group">
                {% for article, eval in zip(Articles, EvalForm.evals) %}
                    {{ eval.hidden_tag() }}
                    <div class="panel panel-primary">
                      <div class="panel-heading"><h2> {{ article.title }} </h2> <br><h4> {{ article.subtitle }} </h4> </div>
                      <div class="panel-body"><p style="font-size:20px"> {{ article.text | safe }} </p></div>
                    </div>
                    <div class="panel panel-primary">
                      <div class="panel-heading"><h5> Your evaluation of this article: </h5> </div>
                      <div class="panel-body">
                        <div class="row">
                            <div class="col-md-8">
                                <p> {{ eval.form.category.label }}: </p> <p> {{ eval.form.category }} </p>
                            </div>
                            <div class="col-md-8">
                                <p> {{ eval.form.comment.label }}: </p> <p> {{ eval.form.comment(rows="1", cols="50") }} </p>
                            </div>
                        </div>
                      </div>
                    </div>
                     <br> <br>
                {% endfor %}
                 </div>
                <div class="panel panel-danger">
                    <div class="panel-heading"><h4>Warning</h4></div>
                    <div class="panel-body"><p style="font-size:20px"> You are about to submit the form.
                        Please double-check that your answers have been entered correctly for each news article.</p></div>
                </div>
                <p> {{ EvalForm.submit(class="btn btn-primary") }} </p>
            </form>
      </div>
</div>
</div>
{% endblock content %}

app/eval/templates/evaluation_results.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
<div class="panel panel-default">
      <div class="panel-heading"><h2>End-of-Form Instructions</h2></div>
      <div class="panel-body">
               Thank you for participating in the survey. If you are an Amazon MTurk worker, please provide this form id in the MTurk survey: <b>{{ form_id }}</b>.
      </div>
</div>
</div>
{% endblock content %}